config/routes.rb
Rails.application.routes.draw do

  # 会員用
  devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

    # ゲストログイン用
    devise_scope :member do
      post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end

  scope module: :public do
    root "homes#top"
    get "/about"=>"homes#about"
    resources :members, only: [:show, :edit, :update, :index]
    get "books/search" => "books#search"
    resources :candidate_posts, only: [:create, :index, :update, :destroy]
    resources :reviews, only: [:create, :index, :show, :edit, :update, :destroy] do
      member do
        get 'new', as: 'new'
        patch 'post', as: 'post'
      end
      resources :comments, only: [:create, :destroy]
    end
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => "homes#top"
    resources :members, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update] do
      resources :comments, only: [:edit, :update]
    end
    resources :tags, only: [:index]
    resources :genre_tags, only: [:create, :edit, :update, :destroy]
    resources :target_age_tags, only: [:create, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate_post.rb
class CandidatePost < ApplicationRecord

  enum consideration_status: { consideration: 0, decision: 1, pending: 2, purchased: 3}

  belongs_to :member

  validates :memo, length: {maximum: 100}

  scope :recent, -> (count) { order(updated_at: :desc).limit(count) }
  scope :extract, -> (member, status) { where(member_id: member.id, consideration_status: status) }

end

app/models/comment.rb
class Comment < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  belongs_to :review

  validates :comment, presence: true, length: {maximum: 1000}

end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord

  has_many :review_genre_tags, dependent: :destroy
  has_many :reviews, through: :review_genre_tags

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum delete_status: { active: false, withdrawal: true }

  has_many :candidate_posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true
  validates :year_of_birth, length: { is: 4}, if: :year_guest?
  validates :email, presence: true
  validates :self_introduction, length: {maximum: 200}

  # ゲストログイン機能用（public/sessionsコントローラで使用）
  def self.guest
    find_or_create_by!(name: 'guestmember' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name_kana = "guestmember"
      member.nickname = "ゲスト会員"
    end
  end

  def year_guest?
    self.email != 'guest@example.com'
  end

end

app/models/review.rb
class Review < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  has_many :comments, dependent: :destroy
  has_many :review_genre_tags, dependent: :destroy
  has_many :genre_tags, through: :review_genre_tags
  has_many :review_target_age_tags, dependent: :destroy
  has_many :target_age_tags, through: :review_target_age_tags

  validates :review, length: {maximum: 3000}
  scope :displayable, -> { where(hidden_status: false).where("LENGTH(review) >= ?", 1) }

  def self.search_for(parameter, keyword)
    if parameter == "title"
      Review.displayable.where("title LIKE?", "%#{keyword}%")
    elsif parameter == "author"
      Review.displayable.where("author LIKE?", "%#{keyword}%")
    elsif parameter == "publisherName"
      Review.displayable.where("publisher LIKE?", "%#{keyword}%")
    elsif parameter == "isbn"
      Review.displayable.where(isbn_code: keyword)
    else
      Review.displayable
    end
  end

end

app/models/review_genre_tag.rb
class ReviewGenreTag < ApplicationRecord

  belongs_to :review
  belongs_to :genre_tag

end

app/models/review_target_age_tag.rb
class ReviewTargetAgeTag < ApplicationRecord

  belongs_to :review
  belongs_to :target_age_tag

end

app/models/target_age_tag.rb
class TargetAgeTag < ApplicationRecord

  has_many :review_target_age_tags, dependent: :destroy
  has_many :reviews, through: :review_target_age_tags

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  before_action :authenticate_admin!

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to admin_review_path(@comment.review_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:hidden_status)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @members = Member.page(params[:page])
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path(@member.id)
    else
      render "edit"
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :name_kana, :nickname, :year_of_birth, :email, :self_introduction, :profile_image, :delete_status)
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @reviews = Review.all.page(params[:page])
  end

  def show
    @review = Review.find(params[:id])
    @comments = Comment.where(review_id: @review.id)
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to admin_reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:hidden_status)
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre_tag = GenreTag.new
    @genre_tags = GenreTag.all
    @target_age_tag = TargetAgeTag.new
    @target_age_tags = TargetAgeTag.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :year_of_birth, :delete_status])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genre_tags_helper.rb
module Admin::GenreTagsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # 会員の大まかな年齢の表示用（将来的に実装予定のプレゼント相手の年齢表示にも使用予定）
  def calc_age(obj)
    Date.today.strftime("%Y%m%d").to_i/10000 - obj.year_of_birth.to_i
  end

end

app/views/admin/comments/edit.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div class="card mb-5">
      <div class="card-header">
        <h5><strong>コメントを非公開にする</strong></h5>
      </div>
      <div class="card-body">
        <%= form_with model: @comment, url: admin_review_comment_path(@comment.review_id, @comment.id) do |f| %>
        <div class="row">
          <div class="col-lg-2 col-md-3 col-12">
            <strong>公開ステータス：</strong>
          </div>
          <div class="col-md-2">
            <%= f.radio_button :hidden_status, "open" %>
              <%= f.label :hidden_status, "公開" %>
          </div>
          <div class="col-md-2">
            <%= f.radio_button :hidden_status, "hidden" %>
              <%= f.label :hidden_status, "非公開" %>
          </div>
          <div class="col-2">
            <%= f.submit "変更を保存", class: 'btn btn-success' %>
          </div>
          <div class="col"></div>
        </div>
        <% end %>
      </div>
      <div class="card-footer bg-transparent">
        <div class="row">
          <div class="col-md-8 col-12">
            <div class="card-body">
              <h4 class="card-title">対象のコメント</h4>
              <p class="card-text"><%= @comment.comment %></p>
            </div>
            <div class="card-footer bg-transparent">
              投稿者：
              <%= link_to admin_member_path(@comment.member_id) do %>
                <%= Member.find(@comment.member_id).nickname %>
              <% end %>
              、投稿日時：<%= l @comment.updated_at %>
            </div>
          </div>

          <div class="col-md-4 col-12">
            <div class="card-body">
              <div class="card-title">
              <%= link_to (image_tag(@comment.review.book_image_url)), @comment.review.rakuten_books_url %>
              </div>
              <h5 class="card-title"><strong><%= @comment.review.title %></strong></h5>
              <h6 class="card-subtitle"><%= @comment.review.author %></h6>
              出版社：<%= @comment.review.publisher %>、
              出版日：<%= @comment.review.date_of_publication %>、
              ISBN：<%= @comment.review.isbn_code %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>