config/routes.rb
Rails.application.routes.draw do

  # 会員用
  devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

    # ゲストログイン用
    devise_scope :member do
      post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end

  scope module: :public do
    root "homes#top"
    get "/about"=>"homes#about"
    resources :members, only: [:show, :edit, :update, :index]
    get "books/search" => "books#search"
    resources :candidate_posts, only: [:create, :index, :update, :destroy]
    resources :reviews, only: [:create, :index, :show, :edit, :update, :destroy] do
      member do
        get 'new', as: 'new'
        patch 'post', as: 'post'
      end
      resources :comments, only: [:create, :destroy]
    end
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => "homes#top"
    resources :members, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update] do
      resources :comments, only: [:edit, :update]
    end
    resources :tags, only: [:index]
    resources :genre_tags, only: [:create, :edit, :update, :destroy]
    resources :target_age_tags, only: [:create, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate_post.rb
class CandidatePost < ApplicationRecord

  enum consideration_status: { consideration: 0, decision: 1, pending: 2, purchased: 3}

  belongs_to :member

  validates :memo, length: {maximum: 100}

  scope :recent, -> (count) { order(updated_at: :desc).limit(count) }
  scope :extract, -> (member, status) { where(member_id: member.id, consideration_status: status) }

end

app/models/comment.rb
class Comment < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  belongs_to :review

  validates :comment, presence: true, length: {maximum: 1000}

end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord

  has_many :review_genre_tags, dependent: :destroy
  has_many :reviews, through: :review_genre_tags

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum delete_status: { active: false, withdrawal: true }

  has_many :candidate_posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true
  validates :year_of_birth, length: { is: 4}, if: :year_guest?
  validates :email, presence: true
  validates :self_introduction, length: {maximum: 200}

  # ゲストログイン機能用（public/sessionsコントローラで使用）
  def self.guest
    find_or_create_by!(name: 'guestmember' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name_kana = "guestmember"
      member.nickname = "ゲスト会員"
    end
  end

  def year_guest?
    self.email != 'guest@example.com'
  end

end

app/models/review.rb
class Review < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  has_many :comments, dependent: :destroy
  has_many :review_genre_tags, dependent: :destroy
  has_many :genre_tags, through: :review_genre_tags
  has_many :review_target_age_tags, dependent: :destroy
  has_many :target_age_tags, through: :review_target_age_tags

  validates :review, length: {maximum: 3000}
  scope :displayable, -> { where(hidden_status: false).where("LENGTH(review) >= ?", 1) }

  def self.search_for(parameter, keyword)
    if parameter == "title"
      Review.displayable.where("title LIKE?", "%#{keyword}%")
    elsif parameter == "author"
      Review.displayable.where("author LIKE?", "%#{keyword}%")
    elsif parameter == "publisherName"
      Review.displayable.where("publisher LIKE?", "%#{keyword}%")
    elsif parameter == "isbn"
      Review.displayable.where(isbn_code: keyword)
    else
      Review.displayable
    end
  end

end

app/models/review_genre_tag.rb
class ReviewGenreTag < ApplicationRecord

  belongs_to :review
  belongs_to :genre_tag

end

app/models/review_target_age_tag.rb
class ReviewTargetAgeTag < ApplicationRecord

  belongs_to :review
  belongs_to :target_age_tag

end

app/models/target_age_tag.rb
class TargetAgeTag < ApplicationRecord

  has_many :review_target_age_tags, dependent: :destroy
  has_many :reviews, through: :review_target_age_tags

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @members = Member.page(params[:page])
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path(@member.id)
    else
      render "edit"
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :name_kana, :nickname, :year_of_birth, :email, :self_introduction, :profile_image, :delete_status)
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @reviews = Review.all.page(params[:page])
  end

  def show
    @review = Review.find(params[:id])
    @comments = Comment.where(review_id: @review.id)
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to admin_reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:hidden_status)
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre_tag = GenreTag.new
    @genre_tags = GenreTag.all
    @target_age_tag = TargetAgeTag.new
    @target_age_tags = TargetAgeTag.all
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :year_of_birth, :delete_status])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genre_tags_helper.rb
module Admin::GenreTagsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # 会員の大まかな年齢の表示用（将来的に実装予定のプレゼント相手の年齢表示にも使用予定）
  def calc_age(obj)
    Date.today.strftime("%Y%m%d").to_i/10000 - obj.year_of_birth.to_i
  end

end

app/views/admin/members/edit.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div class="col-xl-6 col-lg-8 col-md-10 col-12 mx-auto">
      <div class="card shadow mb-5">
        <div class="card-header">
          <h5><strong>会員ステータスの変更</strong></h5>
        </div>
        <div class="card-body">
          <%= @member.nickname %> （<%= @member.name %>、会員No.<%= @member.id %>）さんの会員ステータスを変更する
          <%= form_with model: @member, url: admin_member_path do |f| %>
          <div class="row mt-4 mb-3">
            <div class="col-3">
              <div class="form-check">
                <%= f.radio_button :delete_status, "active" %>
                  <%= f.label :delete_status, "有効" %>
              </div>
            </div>
            <div class="col-3">
              <div class="form-check">
                <%= f.radio_button :delete_status, "withdrawal" %>
                  <%= f.label :delete_status, "退会" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-2">
              <%= f.submit "変更を保存", class: 'btn btn-success' %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/admin/members/index.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div>
      <h3><strong>会員一覧</strong></h3>
    </div>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <table class="table table-hover table-inverse col-md-10 col-12 mt-4 mx-auto">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>ニックネーム（氏名）</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @members.each do |member| %>
        <tr>
          <td><%= member.id %></td>
          <td>
            <%= link_to admin_member_path(member.id) do %>
              <%= member.nickname %> （<%= member.name %>）
            <% end %>
          </td>
          <td><%= member.email %></td>
          <td>
            <%= member.delete_status_i18n %>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="pagination justify-content-center mt-3">
  <%= paginate @members %>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div>
      <h3><strong><%= @member.nickname %> （<%= @member.name %>）さんの詳細</strong></h3>
    </div>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <div class="row">
        <div class="col-lg-6 col-12">
          <table class="table table-hover table-inverse col-10 mt-4 mx-auto">
            <tr>
              <th>会員ID</th>
              <td><%= @member.id %></td>
            </tr>
            <tr>
              <th>名前</th>
              <td><%= @member.name %></td>
            </tr>
            <tr>
              <th>フリガナ</th>
              <td><%= @member.name_kana %></td>
            </tr>
            <tr>
              <th>ニックネーム</th>
              <td><%= @member.nickname %></td>
            </tr>
            <tr>
              <th>生まれ年</th>
              <td><%= @member.year_of_birth %></td>
            </tr>
            <tr>
              <th>メールアドレス</th>
              <td><%= @member.email %></td>
            </tr>
            <tr>
              <th>自己紹介</th>
              <td><%= @member.self_introduction %></td>
            </tr>
            <tr>
              <th>会員ステータス</th>
              <td>
                <%= @member.delete_status_i18n %>
              </td>
            </tr>
          </table>
        </div>
        <div class="col">
          <div class="card-body">
            <h6><strong>プロフィール画像</strong></h6>
            <% if @member.profile_image.attached? %>
              <%= image_tag @member.profile_image, size: "200x200" %>
            <% else %>
              <%= image_tag 'no_image.jpg', size: "200x200" %>
            <% end %>
          </div>
          <div class="card-body">
            <%= link_to "会員ステータスを変更する",  edit_admin_member_path(@member.id), class: "btn btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>