config/routes.rb
Rails.application.routes.draw do

  # 会員用
  devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

    # ゲストログイン用
    devise_scope :member do
      post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end

  scope module: :public do
    root "homes#top"
    get "/about"=>"homes#about"
    resources :members, only: [:show, :edit, :update, :index]
    get "books/search" => "books#search"
    resources :candidate_posts, only: [:create, :index, :update, :destroy]
    resources :reviews, only: [:create, :index, :show, :edit, :update, :destroy] do
      member do
        get 'new', as: 'new'
        patch 'post', as: 'post'
      end
      resources :comments, only: [:create, :destroy]
    end
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => "homes#top"
    resources :members, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update] do
      resources :comments, only: [:edit, :update]
    end
    resources :tags, only: [:index]
    resources :genre_tags, only: [:create, :edit, :update, :destroy]
    resources :target_age_tags, only: [:create, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate_post.rb
class CandidatePost < ApplicationRecord

  enum consideration_status: { consideration: 0, decision: 1, pending: 2, purchased: 3}

  belongs_to :member

  validates :memo, length: {maximum: 100}

  scope :recent, -> (count) { order(updated_at: :desc).limit(count) }
  scope :extract, -> (member, status) { where(member_id: member.id, consideration_status: status) }

end

app/models/comment.rb
class Comment < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  belongs_to :review

  validates :comment, presence: true, length: {maximum: 1000}

end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord

  has_many :review_genre_tags, dependent: :destroy
  has_many :reviews, through: :review_genre_tags

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum delete_status: { active: false, withdrawal: true }

  has_many :candidate_posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true
  validates :year_of_birth, length: { is: 4}, if: :year_guest?
  validates :email, presence: true
  validates :self_introduction, length: {maximum: 200}

  # ゲストログイン機能用（public/sessionsコントローラで使用）
  def self.guest
    find_or_create_by!(name: 'guestmember' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name_kana = "guestmember"
      member.nickname = "ゲスト会員"
    end
  end

  def year_guest?
    self.email != 'guest@example.com'
  end

end

app/models/review.rb
class Review < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  has_many :comments, dependent: :destroy
  has_many :review_genre_tags, dependent: :destroy
  has_many :genre_tags, through: :review_genre_tags
  has_many :review_target_age_tags, dependent: :destroy
  has_many :target_age_tags, through: :review_target_age_tags

  validates :review, length: {maximum: 3000}
  scope :displayable, -> { where(hidden_status: false).where("LENGTH(review) >= ?", 1) }

  def self.search_for(parameter, keyword)
    if parameter == "title"
      Review.displayable.where("title LIKE?", "%#{keyword}%")
    elsif parameter == "author"
      Review.displayable.where("author LIKE?", "%#{keyword}%")
    elsif parameter == "publisherName"
      Review.displayable.where("publisher LIKE?", "%#{keyword}%")
    elsif parameter == "isbn"
      Review.displayable.where(isbn_code: keyword)
    else
      Review.displayable
    end
  end

end

app/models/review_genre_tag.rb
class ReviewGenreTag < ApplicationRecord

  belongs_to :review
  belongs_to :genre_tag

end

app/models/review_target_age_tag.rb
class ReviewTargetAgeTag < ApplicationRecord

  belongs_to :review
  belongs_to :target_age_tag

end

app/models/target_age_tag.rb
class TargetAgeTag < ApplicationRecord

  has_many :review_target_age_tags, dependent: :destroy
  has_many :reviews, through: :review_target_age_tags

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre_tag = GenreTag.new
    @genre_tags = GenreTag.all
    @target_age_tag = TargetAgeTag.new
    @target_age_tags = TargetAgeTag.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :year_of_birth, :delete_status])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genre_tags_helper.rb
module Admin::GenreTagsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # 会員の大まかな年齢の表示用（将来的に実装予定のプレゼント相手の年齢表示にも使用予定）
  def calc_age(obj)
    Date.today.strftime("%Y%m%d").to_i/10000 - obj.year_of_birth.to_i
  end

end

app/views/admin/_header.html.erb
<div class="row d-flex justify-content-center">
  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
      <% if admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "管理者トップ", admin_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "会員一覧", admin_members_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "レビュー一覧", admin_reviews_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "タグ一覧", admin_tags_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_msg.erb
<% if obj.errors.any? %>
  <%= obj.errors.count %>件のエラーが発生しました
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
 <div class="row my-4">
   <div class="text-dark mx-auto">

      <!-- Rakuten Web Services Attribution Snippet FROM HERE -->
      <a href="https://developers.rakuten.com/" target="_blank">Supported by Rakuten Developers</a>
      <!-- Rakuten Web Services Attribution Snippet TO HERE -->

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PictureBookLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="css/bootstrap.css" rel="stylesheet">
  </head>

  <body style="background-color: #FFFFEE;", class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <div class="container">
        <div class="row d-flex justify-content-center my-2">
        <%= link_to root_path do %>
          <%= image_tag 'logo_PBL_M.png' %>
        <% end %>
        </div>
        <% if admin_signed_in? %>
          <%= render 'admin/header' %>
        <% else %>
          <%= render 'public/header' %>
        <% end %>
      </div>
    </header>
    <main class="mb-auto">
    <%= notice %>
    <%= yield %>
    </main>
    <footer style="background-color: #EEEEEE;" class="text-center">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>