config/routes.rb
Rails.application.routes.draw do

  # 会員用
  devise_for :members,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

    # ゲストログイン用
    devise_scope :member do
      post 'members/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end

  scope module: :public do
    root "homes#top"
    get "/about"=>"homes#about"
    resources :members, only: [:show, :edit, :update, :index]
    get "books/search" => "books#search"
    resources :candidate_posts, only: [:create, :index, :update, :destroy]
    resources :reviews, only: [:create, :index, :show, :edit, :update, :destroy] do
      member do
        get 'new', as: 'new'
        patch 'post', as: 'post'
      end
      resources :comments, only: [:create, :destroy]
    end
  end


  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    get '/' => "homes#top"
    resources :members, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update] do
      resources :comments, only: [:edit, :update]
    end
    resources :tags, only: [:index]
    resources :genre_tags, only: [:create, :edit, :update, :destroy]
    resources :target_age_tags, only: [:create, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate_post.rb
class CandidatePost < ApplicationRecord

  enum consideration_status: { consideration: 0, decision: 1, pending: 2, purchased: 3}

  belongs_to :member

  validates :memo, length: {maximum: 100}

  scope :recent, -> (count) { order(updated_at: :desc).limit(count) }
  scope :extract, -> (member, status) { where(member_id: member.id, consideration_status: status) }

end

app/models/comment.rb
class Comment < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  belongs_to :review

  validates :comment, presence: true, length: {maximum: 1000}

end

app/models/genre_tag.rb
class GenreTag < ApplicationRecord

  has_many :review_genre_tags, dependent: :destroy
  has_many :reviews, through: :review_genre_tags

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum delete_status: { active: false, withdrawal: true }

  has_many :candidate_posts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name_kana, presence: true
  validates :nickname, presence: true
  validates :year_of_birth, length: { is: 4}, if: :year_guest?
  validates :email, presence: true
  validates :self_introduction, length: {maximum: 200}

  # ゲストログイン機能用（public/sessionsコントローラで使用）
  def self.guest
    find_or_create_by!(name: 'guestmember' ,email: 'guest@example.com') do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name_kana = "guestmember"
      member.nickname = "ゲスト会員"
    end
  end

  def year_guest?
    self.email != 'guest@example.com'
  end

end

app/models/review.rb
class Review < ApplicationRecord

  enum hidden_status: { open: false, hidden: true }

  belongs_to :member
  has_many :comments, dependent: :destroy
  has_many :review_genre_tags, dependent: :destroy
  has_many :genre_tags, through: :review_genre_tags
  has_many :review_target_age_tags, dependent: :destroy
  has_many :target_age_tags, through: :review_target_age_tags

  validates :review, length: {maximum: 3000}
  scope :displayable, -> { where(hidden_status: false).where("LENGTH(review) >= ?", 1) }

  def self.search_for(parameter, keyword)
    if parameter == "title"
      Review.displayable.where("title LIKE?", "%#{keyword}%")
    elsif parameter == "author"
      Review.displayable.where("author LIKE?", "%#{keyword}%")
    elsif parameter == "publisherName"
      Review.displayable.where("publisher LIKE?", "%#{keyword}%")
    elsif parameter == "isbn"
      Review.displayable.where(isbn_code: keyword)
    else
      Review.displayable
    end
  end

end

app/models/review_genre_tag.rb
class ReviewGenreTag < ApplicationRecord

  belongs_to :review
  belongs_to :genre_tag

end

app/models/review_target_age_tag.rb
class ReviewTargetAgeTag < ApplicationRecord

  belongs_to :review
  belongs_to :target_age_tag

end

app/models/target_age_tag.rb
class TargetAgeTag < ApplicationRecord

  has_many :review_target_age_tags, dependent: :destroy
  has_many :reviews, through: :review_target_age_tags

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @members = Member.page(params[:page])
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      redirect_to admin_member_path(@member.id)
    else
      render "edit"
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :name_kana, :nickname, :year_of_birth, :email, :self_introduction, :profile_image, :delete_status)
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @reviews = Review.all.page(params[:page])
  end

  def show
    @review = Review.find(params[:id])
    @comments = Comment.where(review_id: @review.id)
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to admin_reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:hidden_status)
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre_tag = GenreTag.new
    @genre_tags = GenreTag.all
    @target_age_tag = TargetAgeTag.new
    @target_age_tags = TargetAgeTag.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :nickname, :year_of_birth, :delete_status])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genre_tags_helper.rb
module Admin::GenreTagsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # 会員の大まかな年齢の表示用（将来的に実装予定のプレゼント相手の年齢表示にも使用予定）
  def calc_age(obj)
    Date.today.strftime("%Y%m%d").to_i/10000 - obj.year_of_birth.to_i
  end

end

app/views/admin/homes/top.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div class="col-8 mx-auto">
      <h3><strong>管理者画面です</strong></h3>
    </div>
  </div>
  <div class="row">
    <div class="col-6 mx-auto">
      <%= link_to "会員一覧", admin_members_path, class: 'btn btn-outline-success btn-block' %>
      <%= link_to "レビュー一覧", admin_reviews_path, class: 'btn btn-outline-success btn-block my-3' %>
      <%= link_to "タグ一覧", admin_tags_path, class: 'btn btn-outline-success btn-block' %>
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary btn-block my-5' %>
    </div>
  </div>
</div>

app/views/admin/reviews/_comment.html.erb
<div class="card">
  <ul class="list-group list-group-flush">
    <% review.comments.each do |comment| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-xl-6 col-md-8 col-12">
          <div class="card-text"><%= comment.comment %></div>
          （<%= l comment.created_at %>）
        </div>
        <div class="col-xl-2 col-md-4 col-12 col-2">
          <% if comment.member.profile_image.attached? %>
            <%= image_tag comment.member.profile_image, size: "60x60" %>
          <% else %>
            <%= image_tag 'no_image.jpg', size: "60x60" %>
          <% end %>
          <br>
          <%= comment.member.nickname %>
        </div>
        <div class="col-xl-4 col-12">
          公開ステータス：
          <%= comment.hidden_status_i18n %><br>
          <%= link_to "ステータス変更", edit_admin_review_comment_path(comment.review.id, comment.id), class: "btn btn-outline-secondary btn-sm" %>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/admin/reviews/_review.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-xl-2 col-12">
      <%= link_to admin_member_path(review.member_id) do %>
        <% if Member.find(review.member_id).profile_image.attached? %>
          <%= image_tag Member.find(review.member_id).profile_image, size: "100x100" %>
        <% else %>
          <%= image_tag 'no_image.jpg', size: "100x100" %>
        <% end %>
        <br>
        <%= Member.find(review.member_id).nickname %>
      <% end %>
      </div>
      <div class="col-xl-10 col-12">
        <div class="card-body">
          <p class="card-text"><%= review.review %></p>
        </div>
        <div class="card-footer bg-transparent">
          （<%= l review.updated_at %>）
          公開ステータス：
          <%= review.hidden_status_i18n %>
          <%= link_to "ステータス変更", edit_admin_review_path(review.id), class: "btn btn-outline-secondary btn-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/edit.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div class="card mb-5">
      <div class="card-header">
        <h5><strong>レビューを非公開にする</strong></h5>
      </div>
      <div class="card-body">
        <%= form_with model: @review, url: admin_review_path do |f| %>
        <div class="row">
          <div class="col-lg-2 col-md-3 col-12">
            <strong>公開ステータス：</strong>
          </div>
          <div class="col-md-2">
            <%= f.radio_button :hidden_status, "open" %>
              <%= f.label :hidden_status, "公開" %>
          </div>
          <div class="col-md-2">
            <%= f.radio_button :hidden_status, "hidden" %>
              <%= f.label :hidden_status, "非公開" %>
          </div>
          <div class="col-2">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
          </div>
          <div class="col"></div>
        </div>
        <% end %>
      </div>
      <div class="card-footer bg-transparent">
        <div class="row">
          <div class="col-md-8 col-12">
            <div class="card-body">
              <h4 class="card-title">対象のレビュー</h4>
              <p class="card-text"><%= @review.review %></p>
              ジャンル：
              <% @review.genre_tags.each do |genre_tag| %>
                <%= genre_tag.genre %>
              <% end %>
              、対象年齢：
              <% @review.target_age_tags.each do |target_age_tag| %>
                <%= target_age_tag.target_age %>
              <% end %>
            </div>
            <div class="card-footer bg-transparent">
              投稿者：
              <%= link_to admin_member_path(@review.member_id) do %>
                <%= Member.find(@review.member_id).nickname %>
              <% end %>
              、投稿日時：<%= l @review.updated_at %>
              <br>
              コメント：<%= Comment.where(review_id: @review.id).count %>件
            </div>
          </div>

          <div class="col-md-4 col-12">
            <div class="card-body">
              <div class="card-title">
              <%= link_to (image_tag(@review.book_image_url)), @review.rakuten_books_url %>
              </div>
              <h5 class="card-title"><strong><%= @review.title %></strong></h5>
              <h6 class="card-subtitle"><%= @review.author %></h6>
              出版社：<%= @review.publisher %>、
              出版日：<%= @review.date_of_publication %>、
              ISBN：<%= @review.isbn_code %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<div class="container mb-5">

  <div class="row d-flex flex-column justify-content-center my-5">
    <div>
      <h3><strong>レビュー一覧</strong></h3>
    </div>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <table class="table table-hover table-inverse col-md-10 col-12 mt-4 mx-auto">
        <thead>
          <tr>
            <th>No.</th>
            <th>絵本</th>
            <th>
              レビュー<br>
              （投稿者・更新日時）
            </th>
            <th>公開ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
          <tr>
            <td><%= review.id %></td>
            <td>
              <%= link_to (image_tag(review.book_image_url)), review.rakuten_books_url %><br>
              <%= review.title %>
            </td>
            <td>
              <%= review.review %><br>
              （投稿者：
              <%= link_to admin_member_path(review.member_id) do %>
                <%= Member.find(review.member_id).nickname %>
              <% end %>
              、<%= l review.created_at %>）
              <%= link_to "詳細", admin_review_path(review.id), class: "btn btn-outline-secondary btn-sm" %>
            </td>
            <td>
              <%= review.hidden_status_i18n %><br>
              <%= link_to "ステータス変更", edit_admin_review_path(review.id), class: "btn btn-outline-secondary btn-sm" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="pagination justify-content-center mt-3">
  <%= paginate @reviews %>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div>
      <h3><strong>レビュー詳細</strong></h3>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-md-8 col-12 mb-4">
      <!--レビュー文と投稿者-->
      <%= render 'admin/reviews/review', review: @review %>
      <h5 class="mt-4">■ コメント（<%= @review.comments.count %>件）</h5>
      <%= render 'admin/reviews/comment', review: @review %>
    </div>
    <div class="col-md-4 col-12">
      <%= render 'public/reviews/book', review: @review %>
    </div>
  </div>
  <%= link_to "レビュー一覧に戻る", admin_reviews_path, class: "btn btn-outline-success" %>
</div>

app/views/admin/tags/index.html.erb
<div class="container mb-5">
  <div class="row d-flex flex-column justify-content-center my-5">
    <div>
      <h3><strong>タグ一覧</strong></h3>
    </div>
  </div>
  <div class="row mb-4">
    <!--ジャンルタグの一覧（編集リンク・削除機能を含む）と追加欄-->
    <%= render 'admin/genre_tags/index', genre_tags: @genre_tags, genre_tag: @genre_tag %>
    <!--対象年齢タグの一覧（編集リンク・削除機能を含む）と追加欄-->
    <%= render 'admin/target_age_tags/index', target_age_tags: @target_age_tags, target_age_tag: @target_age_tag %>
  </div>
</div>